### PR TITLE
Fixed refresh logic for shared access signature tokens. Fixed time formatting.

### LINKED ISSUE #1111: Editor mode session expiration
## Bug description/Reproduction steps

After some time, about 15 to 20 minutes, the session of the DevPortal in **editor mode** already expires. To seriously work on pages and contents, a session would need to be at least be 2 hours. 

After the session has expired, an associated warning message pops up AND the content of the screen gets white. 
After the screen got white, you need to close and reopen the DevPortal in editor mode again. All changes that you haven´t explicitly saved in the last session are LOST!!!!!! As you cannot save every 5 minutes without being ineffective, this is a BIG mess.

SessionExpired

This issue occurs already for some weeks and I hoped it would not again me who need to report this problem for the managed approach.

Could it be that you haven´t provided a fix for such issues already several times and such errors occur over time again and again. I am really tired to report this issue again and to request a longer timeout again. It is VERY annoying.

## Expected behavior

Please avoid any data loss and extend the session time to at least 2 hours to be able to seriously work on pages and contents w/o being permanently interrupted. This issue should be fixed for the managed DevPortal in editor mode as soon as possible. 

## Is your portal managed or self-hosted?

**Managed**

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: latest

### PR DESCRIPTION
**Pull request by azaslonov**
Closes #1111, #996.

### CODE REVIEW

File: src/authentication/accessTokenRefresher.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+            });
+
+            const accessTokenHeader = response.headers.find(x => x.name.toLowerCase() === KnownHttpHeaders.OcpApimSasToken.toLowerCase());
+
+            if (!accessTokenHeader) {
+                return;
+            }
+
+            const newAccessToken = AccessToken.parse(accessTokenHeader.value);
+            await this.authenticator.setAccessToken(newAccessToken);
```
Comment (ygrik) [inline src/authentication/accessTokenRefresher.ts:53]: Why don't reuse UsersService.getCurrentUserId?

**Review by ygrik — APPROVED** [review]
