### PR TITLE
Display close account button for users signed in with delegation

### LINKED ISSUE #2042: Cannot close account when using Azure AD or Azure AD B2C Identity Providers
## Bug description

Cannot close account when using Azure AD or Azure AD B2C Identity Providers

## Reproduction steps

1 Configure the Developer portal with Azure AD and/or Azure AD Identity Providers
2. Log in to the Developer Portal with an Azure AD or Azure AD B2C account
3. Navigate to the user profile page
4. Notice that profile data and subscription information is shown but the button to close the account is missing 

## Expected behavior

Regardless of what Identity Provider is used a Developer Portal user should be able to close her/his account. 

## Is your portal managed or self-hosted?

Managed 

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

It seems that the display of the close account-button is conditional, as can be seen here: 

https://github.com/Azure/api-management-developer-portal/blob/master/src/components/users/profile/ko/runtime/profile.html

### PR DESCRIPTION
**Pull request by malincrist**
Closes #2042 , #2052

### CODE REVIEW

File: src/components/users/profile/ko/runtime/profile.ts [hunk 1]
```diff
@@ -143,7 +143,9 @@ export class Profile {
         if (isDelegationApplied) {
             return;
         }
-        const confirmed = window.confirm(`Dear ${this.user().firstName} ${this.user().lastName}, \nYou are about to close your account associated with email address ${this.user().email}.\nYou will not be able to sign in to or restore your closed account. Are you sure you want to close your account?`);
+        const confirmed = window.confirm(
+            this.isBasicAccount() ? `Dear ${this.user().firstName} ${this.user().lastName}, \nYou are about to close your account associated with email address ${this.user().email}.\nYou will not be able to sign in to or restore your closed account. Are you sure you want to close your account?`
+            : `Dear ${this.user().firstName} ${this.user().lastName}, \nYou are about to close your account associated with email address ${this.user().email}.\nAre you sure you want to close your account?`);
```
Comment (f-alizada) [inline src/components/users/profile/ko/runtime/profile.ts:148]: Is there a possibility to move this text to some contants? 
It will be easier to mdify,change in future, and not change html file itself,
What do you think?

Comment (malincrist) [reply src/components/users/profile/ko/runtime/profile.ts]: as discussed, I extracted them in methods, thanks :)

**Review by jsorohova — APPROVED** [review]
